### ISSUE TITLE
Error with getConnInfo in Bun.

### ISSUE THREAD

**Issue by taisan11** [honojs/hono#3208]
### What version of Hono are you using?

4.5.2

### What runtime/platform is your app running on?

Bun

### What steps can reproduce the bug?

```ts
import { Hono } from 'hono'
import { getConnInfo } from 'hono/bun'

const app = new Hono()

app.post('/', async (c) => {
  const body = await c.req.text() //Maybe does not work if it's c.req.* with “await”.
  const IP = getConnInfo(c).remote.address
  return c.text(IP)
})

export default app
```

### What is the expected behavior?

return IP address

### What do you see instead?

Internal Server Error

### Additional information

error message on console
```
 9 |     throw new TypeError("server.requestIP is not a function.");
10 |   }
11 |   const info = server.requestIP(c.req.raw);
12 |   return {
13 |     remote: {
14 |       address: info.address,
                    ^
TypeError: null is not an object (evaluating 'info.address')
      at getConnInfo (hono-error\node_modules\hono\dist\adapter\bun\conninfo.js:14:16)
      at hono-error\src\index.ts:8:14
```

**Comment by EdamAme-x** [comment]
Please try to use `Bun.serve`

**Comment by EdamAme-x** [comment]
It worked in my environment (Bun 1.1.18).
Please give me more information of environment.

**Comment by taisan11** [comment]
Bun version is v1.1.21

**Comment by EdamAme-x** [comment]
It worked on latest Bun 1.1.21.
Try upgrading.

**Comment by yusukebe** [comment]
Hi @taisan11 

This may be a bug. I'll investigate it. Thanks for reporting.

**Comment by yusukebe** [comment]
This is not a Hono's bug but a Bun's matter, though I don't know if it is a real bug or not: https://github.com/oven-sh/bun/issues/11756

**Comment by yusukebe** [comment]
Regarding this issue, we don't have anything we can do. So, I am closing this now.

**Comment by EdamAme-x** [comment]
Looking at the environmental source of the issue, it seems to be a bug on linux.   
I'm using windows, so I may not have been able to reproduce the bug.

**Comment by faytekin** [comment]
I am experiencing the same issue. I am using macOS M3 with Bun version 1.1.21. Not being able to retrieve the IP address is a significant problem.

**Comment by EdamAme-x** [comment]
hi @faytekin 
This problem can be avoided by passing the ip address directly to the env object.
Or by setting it to `Variables` in the frontmost middleware.

**Comment by luksch42** [comment]
Update: https://github.com/oven-sh/bun/issues/11756 was fixed last week. It's working now
