### ISSUE TITLE
Cannot transpile hono using esbuild due to dynamic import of cloudflare:workers when using inspectRoutes

### ISSUE THREAD

**Issue by vaderkos** [honojs/hono#4233]
### What version of Hono are you using?

4.8.0

### What runtime/platform is your app running on? (with version if possible)

Node.js 24.0.2

### What steps can reproduce the bug?

**Description:**
As I'm using Node I do not need `cloudflare:workers` dependency. My application is transpiled using esbuild.
Using inspectRoutes fails transpilation beacuse of dynamic import.

**Steps:**
Try transpiling specified app code using specified esbuild configuration.

### What is the expected behavior?

`inspectRoutes` from `hono/dev` does not dynamically import `cloudflare:workers`. App should be transpilable when using `hono/dev`.

### What do you see instead?

```
Could not resolve "cloudflare:workers"

    ../../node_modules/.pnpm/hono@4.8.0/node_modules/hono/dist/utils/color.js:9:120:
      9 │ ...= "Cloudflare-Workers" ? "NO_COLOR" in ((await import("cloudflare:workers")).env ?? {}) : !getColorEnabled();
        ╵                                                          ~~~~~~~~~~~~~~~~~~~~

  You can mark the path "cloudflare:workers" as external to exclude it from the bundle, which will
  remove this error and leave the unresolved path in the bundle. You can also add ".catch()" here to
  handle this failure at run-time instead of bundle-time.
```

### Additional information

As a workaround I specified `cloudflare:workers` as an external dependency of `esbuild`. 

Esbuild configuration:
```ts
import { resolve } from 'node:path'
import { cwd } from 'node:process'

import { build } from 'esbuild'

const srcDirPath = resolve(cwd(), 'src')
const distDirPath = resolve(cwd(), 'dist')

const entrypoint = resolve(srcDirPath, 'index.ts')
 await build({
  format: 'esm',
  bundle: true,
  minify: true,
  outdir: distDirPath,
  outbase: srcDirPath,
  platform: 'node',
  metafile: true,
  sourcemap: true,
  keepNames: false,
  mainFields: ['module', 'main'],
  treeShaking: true,
  entryPoints: [entrypoint],
  sourcesContent: false,
  // external: ['cloudflare:workers'],
})
```
Transpiled file:
```ts
import { serve } from '@hono/node-server'
import { Hono } from 'hono'
import { inspectRoutes } from 'hono/dev'

const app = new Hono()

app.all('*', (c) => c.text(`Hello ${Date.now()}`))

serve({
  fetch: app.fetch,
  port: 8000,
})

// inspectRoutes adds dynamic import of cloudflare:workers
console.log(inspectRoutes(app))
```

**Comment by HuakunShen** [comment]
For me I was using bun to build hono app and got this error. It was caused by the logger middleware. The error is gone once removed.

**Comment by mehowte** [comment]
Got the same error while trying to deploy hono to aws using sst in version 4.8.0

```
Error: Could not resolve "cloudflare:workers" node_modules/.pnpm/hono@4.8.0/node_modules/hono/dist/utils/color.js:9:120
    at file:///app/.sst/platform/src/components/aws/function.ts:1646:21
    at processTicksAndRejections (node:internal/process/task_queues:95:5) {
  promise: Promise { <rejected> [Circular *1] }
```

**Comment by Gobd** [comment]
Got something like this building my project that worked with 4.7.9 using Bun:

```
9 |   const isNoColor = navigator !== void 0 && navigator.userAgent === "Cloudflare-Workers" ? "NO_COLOR" in ((await import("cloudflare:workers")).env ?? {}) : !getColorEnabled();
                                                                                                                            ^
error: Could not resolve: "cloudflare:workers". Maybe you need to "bun install"?
    at /node_modules/hono/dist/utils/color.js:9:121
```

**Comment by yusukebe** [comment]
Thanks for the reports. We are working on it. Please wait a bit.

**Comment by yusukebe** [comment]
This issue has been fixed in the latest version `v4.8.1` thanks to @ryuapp . Can you try it?

**Comment by Glooper** [comment]
It works for me with SST. Good work @ryuapp and @yusukebe

**Comment by rhkdgns95** [comment]
@yusukebe @Glooper  Hello.

Is this really resolved?
I get the same error in hono@4.8.1?

> terminal
```
# bun@1.2.5
$ bun build --target=bun-linux-x64-modern src/main.ts --target bun --minify --outdir dist
```

> result
```
9 |   const cfWorkers = "cloudflare:workers";
                        ^
error: Could not resolve: "cloudflare:workers". Maybe you need to "bun install"?
    at /Users/kimkwanghoon/Desktop/projects/scraping-event/node_modules/hono/dist/utils/color.js:9:21

9 |   const cfWorkers = "cloudflare:workers";
                        ^
error: Could not resolve: "cloudflare:workers". Maybe you need to "bun install"?
    at /Users/kimkwanghoon/Desktop/projects/scraping-event/node_modules/hono/dist/utils/color.js:9:21
error: script "build:dev" exited with code 1
```

**Comment by yusukebe** [comment]
@rhkdgns95 Thanks. It is reproduced with `bun build` . This issue is not fixed completely.

@ryuapp What do you think of this? Should we wrap it with `try-catch` or do you know a good solution?

**Comment by ryuapp** [comment]
@yusukebe 

> @ryuapp What do you think of this? Should we wrap it with try-catch or do you know a good solution?

Another solution is to declare the variable using `var`/`let`, which makes the variable name indeterminate and avoids analysis even in `bun build`.

**Comment by vaderkos** [comment]
Looks like the exact problem described in issue was resolved in 4.8.1.

**Comment by igoforth** [comment]
I'm getting this error as well on 4.8.1. The weird thing is my app is in a cloudflare worker. Using opennextjs-cloudflare on nextjs 15.3.3. I tried setting 'cloudflare:workers' as an external server package but it didn't help. Removing the logger middleware fixed the issue.

Relevant section of transpiled code
```typescript
async function ac(){let{navigator:e}=globalThis;return!(void 0!==e&&"Cloudflare-Workers"===e.userAgent?"NO_COLOR"in((await r(52570)("cloudflare:workers")).env??{}):!function(){let{process:e,Deno:t}=globalThis;return!("boolean"==typeof t?.noColor?t.noColor:void 0!==e&&"NO_COLOR"in e?.env)}())}
```

Error
```text
Cannot find module 'cloudflare:workers'
```

**Comment by tobimori** [comment]
I have this issue in React Native, it worked with earlier versions (<4.8) of Hono just fine

**Comment by yusukebe** [comment]
Sorry for the trouble. We've released the new version `v4.8.2`, which includes the fix. It can resolve this issue. Thanks @ryuapp

**Comment by rhkdgns95** [comment]
@yusukebe @ryuapp  

Oh.. The issue has been resolved normally in 4.8.2.

Thank you for your quick response!

**Comment by yusukebe** [comment]
I think we can close this issue. If you have any problems with this, please feel free to comment. I'll reopen.

Thanks!

**Comment by jczstudios** [comment]
When using `pnpm wrangler deploy --dry-run`, the bundled file is failing to run in Miniflare:

<img width="1168" height="206" alt="Image" src="https://github.com/user-attachments/assets/9547e3ab-14b2-4569-88c1-cc4bea90136c" />

The bundled function:
```js
async function getColorEnabledAsync() {
  const { navigator: navigator2 } = globalThis;
  const cfWorkers = "cloudflare:workers";
  const isNoColor = navigator2 !== void 0 && navigator2.userAgent === "Cloudflare-Workers" ? await (async () => {
    try {
      return "NO_COLOR" in ((await import(cfWorkers)).env ?? {});
    } catch {
      return false;
    }
  })() : !getColorEnabled();
  return !isNoColor;
}
```
contains a dynamic import that fails.

**Comment by yusukebe** [comment]
@jczstudios Can you create another issue with a minimal project to reproduce it?
