### PR TITLE
fix(types): infer on handlers for path arrays

### LINKED ISSUE #5144: type bug: no overload matches this call (multiple paths + middleware)
### What version of Hono are you using?

4.12.31

### What runtime/platform is your app running on? (with version if possible)

Node 26.4.0, TypeScript 7.0.2

### What steps can reproduce the bug?

This example using multiple paths and middleware in a route won't compile using the latest TypeScript 7.0.2.

Example: 
```ts
import type { HttpBindings } from '@hono/node-server';
import { type Context, Hono, type Next } from 'hono';

type Bindings = HttpBindings & {};

const app = new Hono<{ Bindings: Bindings }>();

const middleware = async (c: Context, next: Next) => {
	console.log('just an example');
	return next();
};

app.on('POST', ['/route1', '/route2'], middleware, (c) => {
	return c.json({ message: 'Hello from route1 or route2' });
});
```

Error:
```
% npm run build

> hono-test@1.0.0 build
> tsc --noEmit

index.ts:13:52 - error TS2769: No overload matches this call.
  The last overload gave the following error.
    Argument of type '(c: Context<any, "/route1" | "/route2", {}>) => JSONRespondReturn<{ message: string; }, ContentfulStatusCode>' is not assignable to parameter of type 'H<any, "/route1" | "/route2", {}, Promise<void>>'.
      Type '(c: Context<any, "/route1" | "/route2", {}>) => JSONRespondReturn<{ message: string; }, ContentfulStatusCode>' is not assignable to type 'Handler<any, "/route1" | "/route2", {}, Promise<void>>'.
        Type 'JSONRespondReturn<{ message: string; }, ContentfulStatusCode>' is missing the following properties from type 'Promise<void>': then, catch, [Symbol.toStringTag], finally

13 app.on('POST', ['/route1', '/route2'], middleware, (c) => {
                                                      ~~~~~~~~

  node_modules/hono/dist/types/types.d.ts:446:5 - The last overload is declared here.
```

tsconfig is default via `npx tsc --init`

Dependencies:
```
"dependencies": {
    "@hono/node-server": "2.0.10",
    "hono": "4.12.31"
  },
  "devDependencies": {
    "@types/node": "26.1.1",
    "typescript": "7.0.2"
  }
```

### What is the expected behavior?

Compile successfully.

### What do you see instead?

_No response_

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by cyphercodes**
Fixes #5144

### The author should do the following, if applicable

- [x] Add tests
- [x] Run tests
- [ ] `bun run format:fix && bun run lint:fix` to format the code
- [ ] Add [TSDoc](https://tsdoc.org/)/[JSDoc](https://jsdoc.app/about-getting-started) to document the code

### Summary

- Add a tuple overload for `app.on(method | method[], path[], middleware, handler)` so middleware returning `next()` does not force the final handler to return `Promise<void>`.
- Strengthen the `OnHandlerInterface` type test to cover the issue's multiple-paths + middleware case and schema inference for both paths.

### Tests

- `npm exec --yes --package typescript@7.0.2 -- tsc --ignoreConfig --noEmit --module ESNext --moduleResolution Bundler --target ESNext --strict --skipLibCheck --types node /tmp/oss-pr-pipeline/hono-5144-repro-after.ts`
- `bun run tsc -p tsconfig.spec.json --noEmit`
- `bunx vitest --run src/types.test.ts`
- `bunx prettier --check src/types.ts src/types.test.ts`
- `bunx eslint src/types.ts src/types.test.ts`

AI assistance was used to prepare this change; I verified the focused repro and test commands above.

### CODE REVIEW

**Comment by yusukebe** [comment]
This fixes only the handler "x2" pattern. We, the maintenance side, will handle the issue. Closing.
