### ISSUE TITLE
Type error when using "moduleResolution": "node16" in tsconfig.

### ISSUE THREAD

**Issue by universse** [honojs/hono#668]
Hi, TypeSript is throw missing type error with the above config.
```
Could not find a declaration file for module 'hono'. '.../hono@2.5.1/node_modules/hono/dist/cjs/index.js' implicitly has an 'any' type.
Try `npm i --save-dev @types/hono` if it exists or add a new declaration (.d.ts) file containing `declare module 'hono';`ts(7016)
```
Related: https://github.com/microsoft/TypeScript/issues/49160

**Comment by yusukebe** [comment]
Hi @universse !

Thank you for creating the issue. I'll investigate to solve it.

**Comment by yusukebe** [comment]
@universse 

It's been fixed and we've released the new version including this patch.

https://github.com/honojs/hono/releases/tag/v2.5.3

Please try it and feel free to reopen the issue.

**Comment by koistya** [comment]
@yusukebe  `"moduleResolution": "NodeNext"` (or, `"NodeNext"`) doesn't seem to work with `2.6.x`

**Comment by yusukebe** [comment]
Hi @koistya !

I've tried it, but that does not throw the errors. I did:

1. Edit `edge/tscondig.json`. Added `"moduleResolution": "NodeNext"`
2. Update Hono to `2.6.2`.
3. `yarn workspace edge build`

Did I do it wrong?

**Comment by koistya** [comment]
@yusukebe run `yarn tsc --build` or, open `edge/index.ts` — VS Code is not be able to load types from `"hono"`.

```
yarn tsc --build

edge/index.ts:17:19 - error TS7006: Parameter 'ctx' implicitly has an 'any' type.

17 app.get("/echo", (ctx) => {
                     ~~~

edge/index.ts:27:23 - error TS7031: Binding element 'req' implicitly has an 'any' type.

27 app.get("*", async ({ req, executionCtx, env }) => {
                         ~~~

edge/index.ts:27:28 - error TS7031: Binding element 'executionCtx' implicitly has an 'any' type.

27 app.get("*", async ({ req, executionCtx, env }) => {
                              ~~~~~~~~~~~~

edge/index.ts:27:42 - error TS7031: Binding element 'env' implicitly has an 'any' type.

27 app.get("*", async ({ req, executionCtx, env }) => {
                                            ~~~


Found 4 errors.
```

**Comment by yusukebe** [comment]
Thank you. Reproduced. I'll investigate.

**Comment by yusukebe** [comment]
@koistya 

This has been fixed #747 by @taishinaritomi .  Thank you for creating the issue, and thanks @taishinaritomi  for a lot work .
I'll release the new including this fix.
