### ISSUE TITLE
type bug: no overload matches this call (multiple paths + middleware)

### ISSUE THREAD

**Issue by cmaas** [honojs/hono#5144]
### What version of Hono are you using?

4.12.31

### What runtime/platform is your app running on? (with version if possible)

Node 26.4.0, TypeScript 7.0.2

### What steps can reproduce the bug?

This example using multiple paths and middleware in a route won't compile using the latest TypeScript 7.0.2.

Example: 
```ts
import type { HttpBindings } from '@hono/node-server';
import { type Context, Hono, type Next } from 'hono';

type Bindings = HttpBindings & {};

const app = new Hono<{ Bindings: Bindings }>();

const middleware = async (c: Context, next: Next) => {
	console.log('just an example');
	return next();
};

app.on('POST', ['/route1', '/route2'], middleware, (c) => {
	return c.json({ message: 'Hello from route1 or route2' });
});
```

Error:
```
% npm run build

> hono-test@1.0.0 build
> tsc --noEmit

index.ts:13:52 - error TS2769: No overload matches this call.
  The last overload gave the following error.
    Argument of type '(c: Context<any, "/route1" | "/route2", {}>) => JSONRespondReturn<{ message: string; }, ContentfulStatusCode>' is not assignable to parameter of type 'H<any, "/route1" | "/route2", {}, Promise<void>>'.
      Type '(c: Context<any, "/route1" | "/route2", {}>) => JSONRespondReturn<{ message: string; }, ContentfulStatusCode>' is not assignable to type 'Handler<any, "/route1" | "/route2", {}, Promise<void>>'.
        Type 'JSONRespondReturn<{ message: string; }, ContentfulStatusCode>' is missing the following properties from type 'Promise<void>': then, catch, [Symbol.toStringTag], finally

13 app.on('POST', ['/route1', '/route2'], middleware, (c) => {
                                                      ~~~~~~~~

  node_modules/hono/dist/types/types.d.ts:446:5 - The last overload is declared here.
```

tsconfig is default via `npx tsc --init`

Dependencies:
```
"dependencies": {
    "@hono/node-server": "2.0.10",
    "hono": "4.12.31"
  },
  "devDependencies": {
    "@types/node": "26.1.1",
    "typescript": "7.0.2"
  }
```

### What is the expected behavior?

Compile successfully.

**Comment by yusukebe** [comment]
Hi @cmaas 

Can you try using `createMiddleware()`? It should resolve your problem.

```ts
import { Hono } from 'hono'
import { createMiddleware } from 'hono/factory'

const app = new Hono()

const middleware = createMiddleware((c, next) => {
  return next()
})

app.on('POST', ['/route1', '/route2'], middleware, (c) => {
  return c.json({ message: 'Hello from route1 or route2' })
})
```

**Comment by cmaas** [comment]
Yes thanks, that works!
